### ISSUE TITLE
Postimage上传图片失败

### ISSUE THREAD

**Issue by VictoireWood** [Redns/picgo-plugin-postimage#1]
用Postimage上传图片失败，打开PicGo的Error Log是这样的。
```log
2022-05-12 00:38:01 [PicGo ERROR] 
------Error Stack Begin------
Error: rename-file conflict
    at Object.handle (%AppData%\picgo\node_modules\picgo-plugin-rename-file\dist\index.js:35:27)
    at async ...\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15714
    at async Promise.all (index 1)
    at async xe.handlePlugins (...\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15636)
    at async xe.beforeUpload (...\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:14734)
    at async xe.start (...\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:13847)
    at async Nt.upload (...\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:55699)
    at async Object.upload (...\PicGo\resources\app.asar\background.js:2:575825)
    at async Oe (...\PicGo\resources\app.asar\background.js:2:578543)
-------Error Stack End------- 
```
设置完全是按照Readme.md来的，不清楚是什么导致的无法上传。

**Comment by Redns** [comment]
这个是插件 `rename-file` 报的错，要去那里提问哦

**Comment by VictoireWood** [comment]
好的，感谢，我把那个插件删掉了就能上传了。麻烦了。
